EnoCard.create!([
                  {text: "Abandon normal instruments"},
                  {text: "Accept advice"},
                  {text: "Accretion"},
                  {text: "A line has two sides"},
                  {text: "Allow an easement (an easement is the abandonment of a stricture)"},
                  {text: "Are there sections? Consider transitions"},
                  {text: "Ask people to work against their better judgement"},
                  {text: "Ask your body"},
                  {text: "Assemble some of the instruments in a group and treat the group"},
                  {text: "Balance the consistency principle with the inconsistency principle"},
                  {text: "Be dirty"},
                  {text: "Breathe more deeply"},
                  {text: "Bridges -build -burn"},
                  {text: "Cascades"},
                  {text: "Change instrument roles"},
                  {text: "Change nothing and continue with immaculate consistency"},
                  {text: "Children's voices -speaking -singing"},
                  {text: "Cluster analysis"},
                  {text: "Consider different fading systems"},
                  {text: "Consult other sources -promising -unpromising"},
                  {text: "Convert a melodic element into a rhythmic element"},
                  {text: "Courage!"},
                  {text: "Cut a vital connection"},
                  {text: "Decorate, decorate"},
                  {text: "Define an area as `safe' and use it as an anchor"},
                  {text: "Destroy -nothing -the most important thing"},
                  {text: "Discard an axiom"},
                  {text: "Disconnect from desire"},
                  {text: "Discover the recipes you are using and abandon them"},
                  {text: "Distorting time"},
                  {text: "Do nothing for as long as possible"},
                  {text: "Don't be afraid of things because they're easy to do"},
                  {text: "Don't be frightened of cliches"},
                  {text: "Don't be frightened to display your talents"},
                  {text: "Don't break the silence"},
                  {text: "Don't stress one thing more than another"},
                  {text: "Do something boring"},
                  {text: "Do the washing up"},
                  {text: "Do the words need changing?"},
                  {text: "Do we need holes?"},
                  {text: "Emphasize differences"},
                  {text: "Emphasize repetitions"},
                  {text: "Emphasize the flaws"},
                  {text: "Faced with a choice, do both (given by Dieter Rot)"},
                  {text: "Feedback recordings into an acoustic situation"},
                  {text: "Fill every beat with something"},
                  {text: "Get your neck massaged"},
                  {text: "Ghost echoes"},
                  {text: "Give the game away"},
                  {text: "Give way to your worst impulse"},
                  {text: "Go slowly all the way round the outside"},
                  {text: "Honor thy error as a hidden intention"},
                  {text: "How would you have done it?"},
                  {text: "Humanize something free of error"},
                  {text: "Imagine the music as a moving chain or caterpillar"},
                  {text: "Imagine the music as a set of disconnected events"},
                  {text: "Infinitesimal gradations"},
                  {text: "Intentions -credibility of -nobility of -humility of"},
                  {text: "Into the impossible"},
                  {text: "Is it finished?"},
                  {text: "Is there something missing?"},
                  {text: "Is the tuning appropriate?"},
                  {text: "Just carry on"},
                  {text: "Left channel, right channel, centre channel"},
                  {text: "Listen in total darkness, or in a very large room, very quietly"},
                  {text: "Listen to the quiet voice"},
                  {text: "Look at a very small object, look at its centre"},
                  {text: "Look at the order in which you do things"},
                  {text: "Look closely at the most embarrassing details and amplify them"},
                  {text: "Lowest common denominator check -single beat -single note -single"},
                  {text: "riff"},
                  {text: "Make a blank valuable by putting it in an exquisite frame"},
                  {text: "Make an exhaustive list of everything you might do and do the last"},
                  {text: "thing on the list"},
                  {text: "Make a sudden, destructive unpredictable action; incorporate"},
                  {text: "Mechanicalize something idiosyncratic"},
                  {text: "Mute and continue"},
                  {text: "Only one element of each kind"},
                  {text: "(Organic) machinery"},
                  {text: "Overtly resist change"},
                  {text: "Put in earplugs"},
                  {text: "Remember those quiet evenings"},
                  {text: "Remove ambiguities and convert to specifics"},
                  {text: "Remove specifics and convert to ambiguities"},
                  {text: "Repetition is a form of change"},
                  {text: "Reverse"},
                  {text: "Short circuit (example: a man eating peas with the idea that they will"},
                  {text: "improve his virility shovels them straight into his lap)"},
                  {text: "Shut the door and listen from outside"},
                  {text: "Simple subtraction"},
                  {text: "Spectrum analysis"},
                  {text: "Take a break"},
                  {text: "Take away the elements in order of apparent non-importance"},
                  {text: "Tape your mouth (given by Ritva Saarikko)"},
                  {text: "The inconsistency principle"},
                  {text: "The tape is now the music"},
                  {text: "Think of the radio"},
                  {text: "Tidy up"},
                  {text: "Trust in the you of now"},
                  {text: "Turn it upside down"},
                  {text: "Twist the spine"},
                  {text: "Use an old idea"},
                  {text: "Use an unacceptable color"},
                  {text: "Use fewer notes"},
                  {text: "Use filters"},
                  {text: "Use `unqualified' people"},
                  {text: "Water"},
                  {text: "What are you really thinking about just now? Incorporate"},
                  {text: "What is the reality of the situation?"},
                  {text: "What mistakes did you make last time?"},
                  {text: "What would your closest friend do?"},
                  {text: "What wouldn't you do?"},
                  {text: "Work at a different speed"},
                  {text: "You are an engineer"},
                  {text: "You can only make one dot at a time"},
                  {text: "You don't have to be ashamed of using your own ideas"}

])
